# This is a basic workflow to help you get started with Actions

name: Scheduled

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/3 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Update `target`
        run: sed -i "/\"target\":/s/\(es\)[0-9]\{4,\}/\1$(date -d '2 years ago' +%Y)/i" tsconfig.json
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.0.3
        with:
          add-paths: ./tsconfig.json
          commit-message: "build: update `target`"
          delete-branch: true
          title: "build: update `target`"

